name: Dockerfile Vulnerabilitiy Scan
on:
  workflow_call:
    inputs:
      dockerfile-path:
        type: string
        required: true
      ecr-tag:
        type: string
        required: false
        default: ${{ github.sha }} 

jobs:
  build:
    name: Image vulnerabilitiy scanner
    runs-on: ubuntu-latest
    steps:
      - id: repo
        uses: ASzc/change-string-case-action@v4
        with:
          string: ${{ github.repository }} 
      - name: Checkout code
        uses: actions/checkout@v3      
      - name: Build image from Dockerfile
        run: |
          docker build --no-cache --force-rm -t ${{ steps.repo.outputs.lowercase }}:${{ inputs.ecr-tag }} -f ${{ inputs.dockerfile-path }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.0.10
        with:
          image-ref: '${{ steps.repo.outputs.lowercase }}:${{ inputs.ecr-tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'